package dhbw.schneider.SpracheX;

public enum TokenType {
	NUMBER, FLOAT, NAME, COMMA, _INVALID, WS, NULL, _EOF, DOUBLEDOT, DOT, COLON, SEMICOLON,
	TYPE,READ,PRINT,
	PROGRAM, BEGIN, END,
	VARIABLE, ASSIGN, PLUS, MINUS, MULTIPLY, DIVIDE,
	ENDDOT
}
